/*
 * Provides CSS named colors.
 * <p>
 * From <a href="http://dev.w3.org/csswg/css-color-4/#named-colors">here</a>.
 */
const CssNamedColor = {
  ALICE_BLUE: "AliceBlue",
  ANTIQUE_WHITE: "AntiqueWhite",
  AQUAMARINE: "Aquamarine",
  AZURE: "Azure",
  BEIGE: "Beige",
  BISQUE: "Bisque",
  BLACK: "Black",
  BLANCHED_ALMOND: "BlanchedAlmond",
  BLUE: "Blue",
  BLUE_VIOLET: "BlueViolet",
  BROWN: "Brown",
  BURLYWOOD: "Burlywood",
  CADET_BLUE: "CadetBlue",
  CHARTREUSE: "Chartreuse",
  CHOCOLATE: "Chocolate",
  CORAL: "Coral",
  CORNFLOWER_BLUE: "CornflowerBlue",
  CORNSILK: "Cornsilk",
  CRIMSON: "Crimson",
  CYAN: "Cyan",
  DARK_BLUE: "DarkBlue",
  DARK_CYAN: "DarkCyan",
  DARK_GOLDENROD: "DarkGoldenrod",
  DARK_GRAY: "DarkGray",
  DARK_GREEN: "DarkGreen",
  DARK_KHAKI: "DarkKhaki",
  DARK_MAGENTA: "DarkMagenta",
  DARK_OLIVE_GREEN: "DarkOliveGreen",
  DARK_ORANGE: "DarkOrange",
  DARK_ORCHID: "DarkOrchid",
  DARK_RED: "DarkRed",
  DARK_SALMON: "DarkSalmon",
  DARK_SEA_GREEN: "DarkSeaGreen",
  DARK_SLATE_BLUE: "DarkSlateBlue",
  DARK_SLATE_GRAY: "DarkSlateGray",
  DARK_TURQUOISE: "DarkTurquoise",
  DARK_VIOLET: "DarkViolet",
  DEEP_PINK: "DeepPink",
  DEEP_SKY_BLUE: "DeepSkyBlue",
  DIM_GRAY: "DimGray",
  DODGER_BLUE: "DodgerBlue",
  FIRE_BRICK: "Firebrick",
  FLORAL_WHITE: "FloralWhite",
  FOREST_GREEN: "ForestGreen",
  GAINSBORO: "Gainsboro",
  GHOST_WHITE: "GhostWhite",
  GOLD: "Gold",
  GOLDENROD: "Goldenrod",
  GRAY: "Gray",
  GREEN: "Green",
  GREEN_YELLOW: "GreenYellow",
  HONEYDEW: "Honeydew",
  HOT_PINK: "HotPink",
  INDIAN_RED: "IndianRed",
  INDIGO: "Indigo",
  IVORY: "Ivory",
  KHAKI: "Khaki",
  LAVENDER: "Lavender",
  LAVENDER_BLUSH: "LavenderBlush",
  LAWN_GREEN: "LawnGreen",
  LEMON_CHIFFON: "LemonChiffon",
  LIGHT_BLUE: "LightBlue",
  LIGHT_CORAL: "LightCoral",
  LIGHT_CYAN: "LightCyan",
  LIGHT_GOLDENROD_YELLOW: "LightGoldenrodYellow",
  LIGHT_GRAY: "LightGray",
  LIGHT_GREEN: "LightGreen",
  LIGHT_PINK: "LightPink",
  LIGHT_SALMON: "LightSalmon",
  LIGHT_SEA_GREEN: "LightSeaGreen",
  LIGHT_SKY_BLUE: "LightSkyBlue",
  LIGHT_SLATE_GRAY: "LightSlateGray",
  LIGHT_STEEL_BLUE: "LightSteelBlue",
  LIGHT_YELLOW: "LightYellow",
  LIME: "Lime",
  LIME_GREEN: "LimeGreen",
  LINEN: "Linen",
  MAGENTA: "Magenta",
  MAROON: "Maroon",
  MEDIUM_AQUAMARINE: "MediumAquamarine",
  MEDIUM_BLUE: "MediumBlue",
  MEDIUM_ORCHID: "MediumOrchid",
  MEDIUM_PURPLE: "MediumPurple",
  MEDIUM_SEA_GREEN: "MediumSeaGreen",
  MEDIUM_SLATE_BLUE: "MediumSlateBlue",
  MEDIUM_SPRING_GREEN: "MediumSpringGreen",
  MEDIUM_TURQUOISE: "MediumTurquoise",
  MEDIUM_VIOLET_RED: "MediumVioletRed",
  MIDNIGHT_BLUE: "MidnightBlue",
  MINT_CREAM: "MintCream",
  MISTY_ROSE: "MistyRose",
  MOCCASIN: "Moccasin",
  NAVAJO_WHITE: "NavajoWhite",
  NAVY: "Navy",
  OLD_LACE: "OldLace",
  OLIVE: "Olive",
  OLIVE_DRAB: "OliveDrab",
  ORANGE: "Orange",
  ORANGE_RED: "OrangeRed",
  ORCHID: "Orchid",
  PALE_GOLDENROD: "PaleGoldenrod",
  PALE_GREEN: "PaleGreen",
  PALE_TURQUOISE: "PaleTurquoise",
  PALE_VIOLET_RED: "PaleVioletRed",
  PAPAYA_WHIP: "PapayaWhip",
  PEACH_PUFF: "PeachPuff",
  PERU: "Peru",
  PINK: "Pink",
  PLUM: "Plum",
  POWDER_BLUE: "PowderBlue",
  PURPLE: "Purple",
  REBECCA_PURPLE: "RebeccaPurple",
  RED: "Red",
  ROSY_BROWN: "RosyBrown",
  ROYAL_BLUE: "RoyalBlue",
  SADDLE_BROWN: "SaddleBrown",
  SALMON: "Salmon",
  SANDY_BROWN: "SandyBrown",
  SEA_GREEN: "SeaGreen",
  SEASHELL: "Seashell",
  SIENNA: "Sienna",
  SILVER: "Silver",
  SKY_BLUE: "SkyBlue",
  SLATE_BLUE: "SlateBlue",
  SLATE_GRAY: "SlateGray",
  SNOW: "Snow",
  SPRING_GREEN: "SpringGreen",
  STEEL_BLUE: "SteelBlue",
  TAN: "Tan",
  TEAL: "Teal",
  THISTLE: "Thistle",
  TOMATO: "Tomato",
  TURQUOISE: "Turquoise",
  VIOLET: "Violet",
  WHEAT: "Wheat",
  WHITE: "White",
  WHITE_SMOKE: "WhiteSmoke",
  YELLOW: "Yellow",
  YELLOW_GREEN: "YellowGreen",

  properties: {
    AliceBlue: {
      hex: "#F0F8FF",
      r: 240,
      g: 248,
      b: 255,
      key: "AliceBlue",
    },
    AntiqueWhite: {
      hex: "#FAEBD7",
      r: 250,
      g: 235,
      b: 215,
      key: "AntiqueWhite",
    },
    Aquamarine: {
      hex: "#7FFFD4",
      r: 127,
      g: 255,
      b: 212,
      key: "Aquamarine",
    },
    Azure: {
      hex: "#F0FFFF",
      r: 240,
      g: 255,
      b: 255,
      key: "Azure",
    },
    Beige: {
      hex: "#F5F5DC",
      r: 245,
      g: 245,
      b: 220,
      key: "Beige",
    },
    Bisque: {
      hex: "#FFE4C4",
      r: 255,
      g: 228,
      b: 196,
      key: "Bisque",
    },
    Black: {
      hex: "#000000",
      r: 0,
      g: 0,
      b: 0,
      key: "Black",
    },
    BlanchedAlmond: {
      hex: "#FFEBCD",
      r: 255,
      g: 235,
      b: 205,
      key: "BlanchedAlmond",
    },
    Blue: {
      hex: "#0000FF",
      r: 0,
      g: 0,
      b: 255,
      key: "Blue",
    },
    BlueViolet: {
      hex: "#8A2BE2",
      r: 138,
      g: 43,
      b: 226,
      key: "BlueViolet",
    },
    Brown: {
      hex: "#A52A2A",
      r: 165,
      g: 42,
      b: 42,
      key: "Brown",
    },
    Burlywood: {
      hex: "#DEB887",
      r: 222,
      g: 184,
      b: 135,
      key: "Burlywood",
    },
    CadetBlue: {
      hex: "#5F9EA0",
      r: 95,
      g: 158,
      b: 160,
      key: "CadetBlue",
    },
    Chartreuse: {
      hex: "#7FFF00",
      r: 127,
      g: 255,
      b: 0,
      key: "Chartreuse",
    },
    Chocolate: {
      hex: "#D2691E",
      r: 210,
      g: 105,
      b: 30,
      key: "Chocolate",
    },
    Coral: {
      hex: "#FF7F50",
      r: 255,
      g: 127,
      b: 80,
      key: "Coral",
    },
    CornflowerBlue: {
      hex: "#6495ED",
      r: 100,
      g: 149,
      b: 237,
      key: "CornflowerBlue",
    },
    Cornsilk: {
      hex: "#FFF8DC",
      r: 255,
      g: 248,
      b: 220,
      key: "Cornsilk",
    },
    Crimson: {
      hex: "#DC143C",
      r: 220,
      g: 20,
      b: 60,
      key: "Crimson",
    },
    Cyan: {
      displayName: "Cyan / Aqua",
      hex: "#00FFFF",
      r: 0,
      g: 255,
      b: 255,
      key: "Cyan",
    },
    DarkBlue: {
      hex: "#00008B",
      r: 0,
      g: 0,
      b: 139,
      key: "DarkBlue",
    },
    DarkCyan: {
      hex: "#008B8B",
      r: 0,
      g: 139,
      b: 139,
      key: "DarkCyan",
    },
    DarkGoldenrod: {
      hex: "#B8860B",
      r: 184,
      g: 134,
      b: 11,
      key: "DarkGoldenrod",
    },
    DarkGray: {
      displayName: "DarkGray / DarkGrey",
      hex: "#A9A9A9",
      r: 169,
      g: 169,
      b: 169,
      key: "DarkGray",
    },
    DarkGreen: {
      hex: "#006400",
      r: 0,
      g: 100,
      b: 0,
      key: "DarkGreen",
    },
    DarkKhaki: {
      hex: "#BDB76B",
      r: 189,
      g: 183,
      b: 107,
      key: "DarkKhaki",
    },
    DarkMagenta: {
      hex: "#8B008B",
      r: 139,
      g: 0,
      b: 139,
      key: "DarkMagenta",
    },
    DarkOliveGreen: {
      hex: "#556B2F",
      r: 85,
      g: 107,
      b: 47,
      key: "DarkOliveGreen",
    },
    DarkOrange: {
      hex: "#FF8C00",
      r: 255,
      g: 140,
      b: 0,
      key: "DarkOrange",
    },
    DarkOrchid: {
      hex: "#9932CC",
      r: 153,
      g: 50,
      b: 204,
      key: "DarkOrchid",
    },
    DarkRed: {
      hex: "#8B0000",
      r: 139,
      g: 0,
      b: 0,
      key: "DarkRed",
    },
    DarkSalmon: {
      hex: "#E9967A",
      r: 233,
      g: 150,
      b: 122,
      key: "DarkSalmon",
    },
    DarkSeaGreen: {
      hex: "#8FBC8F",
      r: 143,
      g: 188,
      b: 143,
      key: "DarkSeaGreen",
    },
    DarkSlateBlue: {
      hex: "#483D8B",
      r: 72,
      g: 61,
      b: 139,
      key: "DarkSlateBlue",
    },
    DarkSlateGray: {
      displayName: "DarkSlateGray / DarkSlateGrey",
      hex: "#2F4F4F",
      r: 47,
      g: 79,
      b: 79,
      key: "DarkSlateGray",
    },
    DarkTurquoise: {
      hex: "#00CED1",
      r: 0,
      g: 206,
      b: 209,
      key: "DarkTurquoise",
    },
    DarkViolet: {
      hex: "#9400D3",
      r: 148,
      g: 0,
      b: 211,
      key: "DarkViolet",
    },
    DeepPink: {
      hex: "#FF1493",
      r: 255,
      g: 20,
      b: 147,
      key: "DeepPink",
    },
    DeepSkyBlue: {
      hex: "#00BFFF",
      r: 0,
      g: 191,
      b: 255,
      key: "DeepSkyBlue",
    },
    DimGray: {
      displayName: "DimGray / DimGrey",
      hex: "#696969",
      r: 105,
      g: 105,
      b: 105,
      key: "DimGray",
    },
    DodgerBlue: {
      hex: "#1E90FF",
      r: 30,
      g: 144,
      b: 255,
      key: "DodgerBlue",
    },
    Firebrick: {
      hex: "#B22222",
      r: 178,
      g: 34,
      b: 34,
      key: "Firebrick",
    },
    FloralWhite: {
      hex: "#FFFAF0",
      r: 255,
      g: 250,
      b: 240,
      key: "FloralWhite",
    },
    ForestGreen: {
      hex: "#228B22",
      r: 34,
      g: 139,
      b: 34,
      key: "ForestGreen",
    },
    Gainsboro: {
      hex: "#DCDCDC",
      r: 220,
      g: 220,
      b: 220,
      key: "Gainsboro",
    },
    GhostWhite: {
      hex: "#F8F8FF",
      r: 248,
      g: 248,
      b: 255,
      key: "GhostWhite",
    },
    Gold: {
      hex: "#FFD700",
      r: 255,
      g: 215,
      b: 0,
      key: "Gold",
    },
    Goldenrod: {
      hex: "#DAA520",
      r: 218,
      g: 165,
      b: 32,
      key: "Goldenrod",
    },
    Gray: {
      displayName: "Gray / Grey",
      hex: "#808080",
      r: 128,
      g: 128,
      b: 128,
      key: "Gray",
    },
    Green: {
      hex: "#008000",
      r: 0,
      g: 128,
      b: 0,
      key: "Green",
    },
    GreenYellow: {
      hex: "#ADFF2F",
      r: 173,
      g: 255,
      b: 47,
      key: "GreenYellow",
    },
    Honeydew: {
      hex: "#F0FFF0",
      r: 240,
      g: 255,
      b: 240,
      key: "Honeydew",
    },
    HotPink: {
      hex: "#FF69B4",
      r: 255,
      g: 105,
      b: 180,
      key: "HotPink",
    },
    IndianRed: {
      hex: "#CD5C5C",
      r: 205,
      g: 92,
      b: 92,
      key: "IndianRed",
    },
    Indigo: {
      hex: "#4B0082",
      r: 75,
      g: 0,
      b: 130,
      key: "Indigo",
    },
    Ivory: {
      hex: "#FFFFF0",
      r: 255,
      g: 255,
      b: 240,
      key: "Ivory",
    },
    Khaki: {
      hex: "#F0E68C",
      r: 240,
      g: 230,
      b: 140,
      key: "Khaki",
    },
    Lavender: {
      hex: "#E6E6FA",
      r: 230,
      g: 230,
      b: 250,
      key: "Lavender",
    },
    LavenderBlush: {
      hex: "#FFF0F5",
      r: 255,
      g: 240,
      b: 245,
      key: "LavenderBlush",
    },
    LawnGreen: {
      hex: "#7CFC00",
      r: 124,
      g: 252,
      b: 0,
      key: "LawnGreen",
    },
    LemonChiffon: {
      hex: "#FFFACD",
      r: 255,
      g: 250,
      b: 205,
      key: "LemonChiffon",
    },
    LightBlue: {
      hex: "#ADD8E6",
      r: 173,
      g: 216,
      b: 230,
      key: "LightBlue",
    },
    LightCoral: {
      hex: "#F08080",
      r: 240,
      g: 128,
      b: 128,
      key: "LightCoral",
    },
    LightCyan: {
      hex: "#E0FFFF",
      r: 224,
      g: 255,
      b: 255,
      key: "LightCyan",
    },
    LightGoldenrodYellow: {
      hex: "#FAFAD2",
      r: 250,
      g: 250,
      b: 210,
      key: "LightGoldenrodYellow",
    },
    LightGray: {
      displayName: "LightGray / LightGrey",
      hex: "#D3D3D3",
      r: 211,
      g: 211,
      b: 211,
      key: "LightGray",
    },
    LightGreen: {
      hex: "#90EE90",
      r: 144,
      g: 238,
      b: 144,
      key: "LightGreen",
    },
    LightPink: {
      hex: "#FFB6C1",
      r: 255,
      g: 182,
      b: 193,
      key: "LightPink",
    },
    LightSalmon: {
      hex: "#FFA07A",
      r: 255,
      g: 160,
      b: 122,
      key: "LightSalmon",
    },
    LightSeaGreen: {
      hex: "#20B2AA",
      r: 32,
      g: 178,
      b: 170,
      key: "LightSeaGreen",
    },
    LightSkyBlue: {
      hex: "#87CEFA",
      r: 135,
      g: 206,
      b: 250,
      key: "LightSkyBlue",
    },
    LightSlateGray: {
      displayName: "LightSlateGray / LightSlateGrey",
      hex: "#778899",
      r: 119,
      g: 136,
      b: 153,
      key: "LightSlateGray",
    },
    LightSteelBlue: {
      hex: "#B0C4DE",
      r: 176,
      g: 196,
      b: 222,
      key: "LightSteelBlue",
    },
    LightYellow: {
      hex: "#FFFFE0",
      r: 255,
      g: 255,
      b: 224,
      key: "LightYellow",
    },
    Lime: {
      hex: "#00FF00",
      r: 0,
      g: 255,
      b: 0,
      key: "Lime",
    },
    LimeGreen: {
      hex: "#32CD32",
      r: 50,
      g: 205,
      b: 50,
      key: "LimeGreen",
    },
    Linen: {
      hex: "#FAF0E6",
      r: 250,
      g: 240,
      b: 230,
      key: "Linen",
    },
    Magenta: {
      displayName: "Magenta / Fuchsia",
      hex: "#FF00FF",
      r: 255,
      g: 0,
      b: 255,
      key: "Magenta",
    },
    Maroon: {
      hex: "#800000",
      r: 128,
      g: 0,
      b: 0,
      key: "Maroon",
    },
    MediumAquamarine: {
      hex: "#66CDAA",
      r: 102,
      g: 205,
      b: 170,
      key: "MediumAquamarine",
    },
    MediumBlue: {
      hex: "#0000CD",
      r: 0,
      g: 0,
      b: 205,
      key: "MediumBlue",
    },
    MediumOrchid: {
      hex: "#BA55D3",
      r: 186,
      g: 85,
      b: 211,
      key: "MediumOrchid",
    },
    MediumPurple: {
      hex: "#9370DB",
      r: 147,
      g: 112,
      b: 219,
      key: "MediumPurple",
    },
    MediumSeaGreen: {
      hex: "#3CB371",
      r: 60,
      g: 179,
      b: 113,
      key: "MediumSeaGreen",
    },
    MediumSlateBlue: {
      hex: "#7B68EE",
      r: 123,
      g: 104,
      b: 238,
      key: "MediumSlateBlue",
    },
    MediumSpringGreen: {
      hex: "#00FA9A",
      r: 0,
      g: 250,
      b: 154,
      key: "MediumSpringGreen",
    },
    MediumTurquoise: {
      hex: "#48D1CC",
      r: 72,
      g: 209,
      b: 204,
      key: "MediumTurquoise",
    },
    MediumVioletRed: {
      hex: "#C71585",
      r: 199,
      g: 21,
      b: 133,
      key: "MediumVioletRed",
    },
    MidnightBlue: {
      hex: "#191970",
      r: 25,
      g: 25,
      b: 112,
      key: "MidnightBlue",
    },
    MintCream: {
      hex: "#F5FFFA",
      r: 245,
      g: 255,
      b: 250,
      key: "MintCream",
    },
    MistyRose: {
      hex: "#FFE4E1",
      r: 255,
      g: 228,
      b: 225,
      key: "MistyRose",
    },
    Moccasin: {
      hex: "#FFE4B5",
      r: 255,
      g: 228,
      b: 181,
      key: "Moccasin",
    },
    NavajoWhite: {
      hex: "#FFDEAD",
      r: 255,
      g: 222,
      b: 173,
      key: "NavajoWhite",
    },
    Navy: {
      hex: "#000080",
      r: 0,
      g: 0,
      b: 128,
      key: "Navy",
    },
    OldLace: {
      hex: "#FDF5E6",
      r: 253,
      g: 245,
      b: 230,
      key: "OldLace",
    },
    Olive: {
      hex: "#808000",
      r: 128,
      g: 128,
      b: 0,
      key: "Olive",
    },
    OliveDrab: {
      hex: "#6B8E23",
      r: 107,
      g: 142,
      b: 35,
      key: "OliveDrab",
    },
    Orange: {
      hex: "#FFA500",
      r: 255,
      g: 165,
      b: 0,
      key: "Orange",
    },
    OrangeRed: {
      hex: "#FF4500",
      r: 255,
      g: 69,
      b: 0,
      key: "OrangeRed",
    },
    Orchid: {
      hex: "#DA70D6",
      r: 218,
      g: 112,
      b: 214,
      key: "Orchid",
    },
    PaleGoldenrod: {
      hex: "#EEE8AA",
      r: 238,
      g: 232,
      b: 170,
      key: "PaleGoldenrod",
    },
    PaleGreen: {
      hex: "#98FB98",
      r: 152,
      g: 251,
      b: 152,
      key: "PaleGreen",
    },
    PaleTurquoise: {
      hex: "#AFEEEE",
      r: 175,
      g: 238,
      b: 238,
      key: "PaleTurquoise",
    },
    PaleVioletRed: {
      hex: "#DB7093",
      r: 219,
      g: 112,
      b: 147,
      key: "PaleVioletRed",
    },
    PapayaWhip: {
      hex: "#FFEFD5",
      r: 255,
      g: 239,
      b: 213,
      key: "PapayaWhip",
    },
    PeachPuff: {
      hex: "#FFDAB9",
      r: 255,
      g: 218,
      b: 185,
      key: "PeachPuff",
    },
    Peru: {
      hex: "#CD853F",
      r: 205,
      g: 133,
      b: 63,
      key: "Peru",
    },
    Pink: {
      hex: "#FFC0CB",
      r: 255,
      g: 192,
      b: 203,
      key: "Pink",
    },
    Plum: {
      hex: "#DDA0DD",
      r: 221,
      g: 160,
      b: 221,
      key: "Plum",
    },
    PowderBlue: {
      hex: "#B0E0E6",
      r: 176,
      g: 224,
      b: 230,
      key: "PowderBlue",
    },
    Purple: {
      hex: "#800080",
      r: 128,
      g: 0,
      b: 128,
      key: "Purple",
    },
    RebeccaPurple: {
      hex: "#663399",
      r: 102,
      g: 51,
      b: 153,
      key: "RebeccaPurple",
    },
    Red: {
      hex: "#FF0000",
      r: 255,
      g: 0,
      b: 0,
      key: "Red",
    },
    RosyBrown: {
      hex: "#BC8F8F",
      r: 188,
      g: 143,
      b: 143,
      key: "RosyBrown",
    },
    RoyalBlue: {
      hex: "#4169E1",
      r: 65,
      g: 105,
      b: 225,
      key: "RoyalBlue",
    },
    SaddleBrown: {
      hex: "#8B4513",
      r: 139,
      g: 69,
      b: 19,
      key: "SaddleBrown",
    },
    Salmon: {
      hex: "#FA8072",
      r: 250,
      g: 128,
      b: 114,
      key: "Salmon",
    },
    SandyBrown: {
      hex: "#F4A460",
      r: 244,
      g: 164,
      b: 96,
      key: "SandyBrown",
    },
    SeaGreen: {
      hex: "#2E8B57",
      r: 46,
      g: 139,
      b: 87,
      key: "SeaGreen",
    },
    Seashell: {
      hex: "#FFF5EE",
      r: 255,
      g: 245,
      b: 238,
      key: "Seashell",
    },
    Sienna: {
      hex: "#A0522D",
      r: 160,
      g: 82,
      b: 45,
      key: "Sienna",
    },
    Silver: {
      hex: "#C0C0C0",
      r: 192,
      g: 192,
      b: 192,
      key: "Silver",
    },
    SkyBlue: {
      hex: "#87CEEB",
      r: 135,
      g: 206,
      b: 235,
      key: "SkyBlue",
    },
    SlateBlue: {
      hex: "#6A5ACD",
      r: 106,
      g: 90,
      b: 205,
      key: "SlateBlue",
    },
    SlateGray: {
      displayName: "SlateGray / SlateGrey",
      hex: "#708090",
      r: 112,
      g: 128,
      b: 144,
      key: "SlateGray",
    },
    Snow: {
      hex: "#FFFAFA",
      r: 255,
      g: 250,
      b: 250,
      key: "Snow",
    },
    SpringGreen: {
      hex: "#00FF7F",
      r: 0,
      g: 255,
      b: 127,
      key: "SpringGreen",
    },
    SteelBlue: {
      hex: "#4682B4",
      r: 70,
      g: 130,
      b: 180,
      key: "SteelBlue",
    },
    Tan: {
      hex: "#D2B48C",
      r: 210,
      g: 180,
      b: 140,
      key: "Tan",
    },
    Teal: {
      hex: "#008080",
      r: 0,
      g: 128,
      b: 128,
      key: "Teal",
    },
    Thistle: {
      hex: "#D8BFD8",
      r: 216,
      g: 191,
      b: 216,
      key: "Thistle",
    },
    Tomato: {
      hex: "#FF6347",
      r: 255,
      g: 99,
      b: 71,
      key: "Tomato",
    },
    Turquoise: {
      hex: "#40E0D0",
      r: 64,
      g: 224,
      b: 208,
      key: "Turquoise",
    },
    Violet: {
      hex: "#EE82EE",
      r: 238,
      g: 130,
      b: 238,
      key: "Violet",
    },
    Wheat: {
      hex: "#F5DEB3",
      r: 245,
      g: 222,
      b: 179,
      key: "Wheat",
    },
    White: {
      hex: "#FFFFFF",
      r: 255,
      g: 255,
      b: 255,
      key: "White",
    },
    WhiteSmoke: {
      hex: "#F5F5F5",
      r: 245,
      g: 245,
      b: 245,
      key: "WhiteSmoke",
    },
    Yellow: {
      hex: "#FFFF00",
      r: 255,
      g: 255,
      b: 0,
      key: "Yellow",
    },
    YellowGreen: {
      hex: "#9ACD32",
      r: 154,
      g: 205,
      b: 50,
      key: "YellowGreen",
    },
  },
};

CssNamedColor.keys = () => Object.keys(CssNamedColor.properties);

CssNamedColor.values = () => Object.values(CssNamedColor.properties);

Object.freeze(CssNamedColor);

module.exports = CssNamedColor;
